version: '3.8'

services:
  server:
    build:
      context: ./backEnd
    restart: always
    env_file:
      - ./backEnd/.env
    expose:
      - "8000"
    volumes:
      - media:/backEnd/media/
    depends_on:
      - db
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backEnd/.env.db
    expose:
      - "5432"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./frontEnd/dist:/home/app/
    depends_on:
      - server

volumes:
    postgres_data:
    media:
