# Generated by Django 4.0.4 on 2022-12-18 10:02

import apps.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=apps.users.models.user.ChoiceArrayField(base_field=models.CharField(choices=[('director', 'Director'), ('warehouseman', 'Warehouseman'), ('salesman', 'Salesman'), ('financier', 'Financier'), ('default', 'Default')], max_length=12), default=['default'], size=None),
        ),
    ]
