# Generated by Django 4.0.4 on 2023-01-03 13:35

import apps.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('warehouseman', 'Warehouseman'), ('salesman', 'Salesman'), ('financier', 'Financier'), ('default', 'Default')], max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=apps.users.models.user.ChoiceArrayField(base_field=models.CharField(choices=[('director', 'Director'), ('warehouseman', 'Warehouseman'), ('salesman', 'Salesman'), ('financier', 'Financier'), ('default', 'Default')], max_length=12), default=apps.users.models.user.get_default_role, size=None),
        ),
    ]
