# Generated by Django 4.0.4 on 2023-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_code_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
