# Generated by Django 4.0.4 on 2023-01-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inputinvoice'),
        ),
    ]
