# Generated by Django 4.0.4 on 2023-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_inputinvoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
