# Generated by Django 4.0.4 on 2023-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_inputinvoiceitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputinvoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='outputinvoice',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='outputinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.outputinvoice'),
        ),
    ]
