# Generated by Django 4.0.4 on 2023-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_inputinvoice_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedinvoice',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='outputinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnedinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
