# Generated by Django 4.0.4 on 2023-02-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_client_is_deleted'),
        ('warehouse', '0011_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='warehouse.supplier'),
        ),
        migrations.AlterField(
            model_name='outputinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.client'),
        ),
        migrations.AlterField(
            model_name='outputinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_items', to='warehouse.product'),
        ),
        migrations.AlterField(
            model_name='returnedinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.returnedinvoice'),
        ),
    ]
