# Generated by Django 4.0.4 on 2023-01-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for_input_invoice', 'For Input Invoice'), ('for_returned_invoice', 'For Returned Invoice'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('from_outside', 'From Outside'), ('from_sales', 'From Sales')], db_index=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.outputinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.costtype')),
                ('input_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.inputinvoice')),
                ('returned_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.returnedinvoice')),
            ],
        ),
    ]
