# Generated by Django 4.0.4 on 2023-01-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_remove_returnedinvoice_is_deleted_and_more'),
        ('finance', '0003_remove_costtype_choice_remove_expense_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='input_invoice',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='warehouse.inputinvoice'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='returned_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='warehouse.returnedinvoice'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='warehouse.outputinvoice'),
        ),
    ]
