# Generated by Django 4.0.4 on 2023-02-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_description_income_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='cost_type',
        ),
        migrations.DeleteModel(
            name='CostType',
        ),
    ]
